### ISSUE TITLE
Testing for Django

### ISSUE THREAD

**Issue by UPstartDeveloper** [escofresco/tinydoor#25]
Look in separate tests settings files in config folder

Time est. 9 hours

**Comment by UPstartDeveloper** [comment]
In Sprint 3, it will be of utmost importance to **add tests, especially for the doorknob folder**. @uyennguyen16900 could you please lend a hand in this?

I also plan to collaborate with you on this, it's just for this coming Sprint 3 I also want to focus on developing the pitch deck.

Here is the link to the [Django docs that is about testing ](https://docs.djangoproject.com/en/3.0/topics/testing/).
As well this is a little bit more advanced testing framework called [Hypothesis](https://pypi.org/project/hypothesis/). I've never used it, Jonasz told me about it and I think it may come in handy.

**Comment by uyennguyen16900** [comment]
Absolutely. I will take a look at the django docs and Hypothesis as well.
